#!/bin/bash
./Measure_SOS_bias_log_liklihood_in_BART_Germany_Female_LMs.sh
./Measure_SOS_bias_log_liklihood_in_BART_Germany_Male_LMs.sh
./Measure_SOS_bias_log_liklihood_in_BART_Germany_Non_Binary_LMs.sh
