#!/bin/bash
./Measure_SOS_bias_log_liklihood_in_bert-base_US_Female_LMs.sh
./Measure_SOS_bias_log_liklihood_in_bert-base_US_Male_LMs.sh
./Measure_SOS_bias_log_liklihood_in_bert-base_US_Non_Binary_LMs.sh
