#!/bin/bash
./Measure_SOS_bias_log_liklihood_in_bert-base_UK_Female_LMs.sh
./Measure_SOS_bias_log_liklihood_in_bert-base_UK_Male_LMs.sh
./Measure_SOS_bias_log_liklihood_in_bert-base_UK_Non_Binary_LMs.sh
